const initialGifts = [
  {
    name: "Knowledge Encyclopedia: World History",
    description: "This encyclopedia provides comprehensive answers to questions about the emergence of civilizations, Britain's role in the Industrial Revolution, and the Suffrage Movement. With easy-to-understand diagrams and a glossary, it's perfect for curious minds. Packed with fun facts, it's a must-read for children, making learning engaging and accessible.",
    image: "https://m.media-amazon.com/images/I/91iVhQR8l8L._SY466_.jpg",
    price: 17.99,
    buyUrl: "https://www.amazon.com/Knowledge-Encyclopedia-Wonder-House-Books/dp/9354404510/ref=sr_1_11_sspa?crid=JMJ57HMGEBN&keywords=History+Book&qid=1707326013&sprefix=history+book%2Caps%2C137&sr=8-11-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1",
    keywords: ["history", "book", "reading"],
  },
  {
    name: "The Martian: A Novel",
    description:"In this gripping tale, astronaut Mark Watney finds himself stranded on Mars after a dust storm separates him from his crew. With limited supplies and daunting challenges, Watney must rely on his ingenuity and resilience to survive against impossible odds. A celebration of human determination and ingenuity, this novel is a thrilling adventure that keeps readers on the edge of their seats",
    image: "https://m.media-amazon.com/images/I/51QimqeXMXL._SY466_.jpg",
    price: 17.69,
    buyUrl: "https://www.amazon.com/Martian-Novel-Andy-Weir/dp/0804139024/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326135&sr=8-9",
    keywords: ["sci-fi", "book", "reading"],
  },
  {
    name: "True Crime Case Histories",
    description:"Warning: This true crime collection dives deep into gruesome details, offering a raw look at the minds of killers. Not for the faint-hearted, these stories unveil the dark side of humanity, leaving nothing out. Brace yourself for a chilling exploration of the human psyche.",
    image: "https://m.media-amazon.com/images/I/71EBCyc0xBL._SY466_.jpg",
    price: 29.99,
    buyUrl: "https://www.amazon.com/True-Crime-Case-Histories-Disturbing/dp/1956566228/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326300&sr=8-2-spons",
    keywords: ["crime","book", "reading"],
  },
  {
    name: "Icebreaker: A Novel",
    description:"Figure skater Ana dreams of Team USA. But a twist of fate lands her on the same ice as hockey captain Nate. Sparks fly, but with Ana's future at stake, she might need Nate's help. Can love thaw their icy relationship?",
    image: "https://m.media-amazon.com/images/I/71nKtAPngQL._SY466_.jpg",
    price: 11.32,
    buyUrl: "https://www.amazon.com/Icebreaker-Novel-Maple-Hannah-Grace/dp/1668026031/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1707326450&sr=8-7",
    keywords: ["romantic","book", "reading"],
  },
  {
    name: "A Court of Thorns and Roses",
    description: "When huntress Feyre kills a wolf, she's taken to a magical realm by a faerie. But he's not just a beast—he's Tamlin, a lethal immortal. As Feyre's icy feelings thaw into passion, she uncovers a dark threat looming over the faerie lands. Can she save Tamlin's world before it's too late?",
    image: "https://m.media-amazon.com/images/I/81LftCZRUML._SY466_.jpg",
    price: 17.59,
    buyUrl: "https://www.amazon.com/Court-Thorns-Roses-Sarah-Maas/dp/1635575559/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326623&sr=8-6",
    keywords: ["fantasy","book", "reading"],
  },
  {
    name: "Hidden Pictures: A Novel",
    description: "Fresh out of rehab, Mallory becomes a nanny for Teddy, a sweet boy with a disturbing secret. His drawings hint at a sinister past, leading Mallory into a supernatural mystery. Can she unravel the truth before it's too late?",
    image: "https://m.media-amazon.com/images/I/91puw8POkwL._SY466_.jpg",
    price: 14.73,
    buyUrl: "https://www.amazon.com/Hidden-Pictures-Novel-Jason-Rekulak/dp/1250819342/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326722&sr=8-6",
    keywords: ["horror","book", "reading"],
  },
  {
    name: "An Innocent Client: A Legal Thriller",
    description: "A preacher's murder in a Tennessee motel implicates a mysterious young girl. Criminal defense lawyer Joe Dillard, despite personal struggles, takes on her case, torn between career and conscience. Rich characters and a surprising plot twist mark this debut novel, leaving readers eager for more.",
    image: "https://m.media-amazon.com/images/I/51zSDpDOibL._SY445_SX342_.jpg",
    price: 24.99,
    buyUrl: "https://www.amazon.com/Innocent-Client-Legal-Thriller-Dillard/dp/1944083103/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326866&sr=8-3-spons",
    keywords: ["mystery","book", "reading"],
  },
  {
    name: "Dragons Love Farts: They're More Fun Than Tacos!",
    description: "Get ready for a laugh-out-loud adventure with Dragons Love Farts! Packed with hilarious memes and silly dragons, this book is perfect for kids who love to giggle. From historical events like Woodstock to literary nods and bedtime stories, Dragons Love Farts is sure to entertain kids again and again. It's the ultimate funny book for boys aged 4-6 or kids aged 5-7, with rhymes reminiscent of Dr. Seuss and illustrations that spark curiosity. Don't miss out on the fun - grab your copy today! 🐉💨",
    image: "https://m.media-amazon.com/images/I/619ZUIo+baL._SY466_.jpg",
    price: 12.35,
    buyUrl: "https://www.amazon.com/Dragons-Love-Farts-Theyre-Tacos/dp/1951696077/ref=sr_1_1_sspa?crid=1R16U8VIEDHAQ&keywords=kid+book&qid=1707326983&sprefix=kid+book%2Caps%2C140&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["child","book","reading","childrens"],
  },
  {
    name: "Samsung 98-Inch Neo QLED 4k Smart TV",
    description:
      "The Samsung QN90A Smart TV delivers stunning picture quality with Quantum HDR 32X and Quantum Matrix Technology, providing vibrant colors and impeccable contrast. Experience immersive sound with Object Tracking Sound+ technology, while the Ultra Viewing Angle ensures optimal viewing from any seat.",
    image: "https://m.media-amazon.com/images/I/913+l9CB6cL._AC_SX679_.jpg",
    price: 9997.99,
    buyUrl:
      "https://www.amazon.com/SAMSUNG-98-Inch-Quantum-Tracking-QN98QN90AAFXZA/dp/B097FDNQ69/ref=sr_1_3?crid=ED7H232QXR29&keywords=tv+expensive&qid=1707324960&sprefix=tv+expensive%2Caps%2C137&sr=8-3&ufe=app_do%3Aamzn1.fos.17f26c18-b61b-4ce9-8a28-de351f41cffb",
    keywords: ["expensive", "tech", "tv"],
  },
  {
    name: "LG 50-Inch 4k Smart TV",
    description:
      "The LG 4K UHD TV offers a smart viewing experience with access to 300+ free LG Channels and FILMMAKER MODE for cinematic visuals. Enjoy HDR10 Pro for vibrant contrast and AI-powered upscaling to 4K. With LG webOS 23, find your favorite apps easily with Quick Cards and enhance your gaming experience with LG Game Optimizer and GeForce NOW.",
    image: "https://m.media-amazon.com/images/I/91MAjR2HydL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    price: 396.99,
    buyUrl: "https://www.amazon.com/LG-50-Inch-Bluetooth-Ethernet-AI-Powered/dp/B0BVXDQYQB/ref=sr_1_10?crid=1BKSGITXYSE9H&keywords=tv%2Bmid%2Brange&qid=1707325735&sprefix=tv%2Bmid%2Brange%2Caps%2C149&sr=8-10&ufe=app_do%3Aamzn1.fos.c3015c4a-46bb-44b9-81a4-dc28e6d374b3&th=1",
    keywords: ["affordable","tech","tv"],
  },
  {
    name: "Amazon Fire TV 32-Inch Smart TV",
    description: "The Fire TV 2-Series offers brilliant 720p HD resolution with HDR 10 support and Dolby Digital Audio. Access 1 million movies and TV episodes, with 200,000 available for free, from any room in your home. Use the Fire TV Alexa Voice Remote for easy navigation and control of your entertainment and smart home devices",
    image: "https://m.media-amazon.com/images/I/418UoVylqyL._AC_SY450_.jpg",
    price: 119.99,
    buyUrl: "https://www.amazon.com/introducing-amazon-fire-tv-32-inch-2-series-hd-smart-tv/dp/B09N6F9NV3/ref=sr_1_4?crid=1J1PVDG3Z5G8&keywords=tv%2Bcheap&qid=1707325364&sprefix=tv%2Bcheap%2Caps%2C161&sr=8-4&th=1",
    keywords: ["cheap","tech","tv"],
  },
  {
    name: "Amazon Essentials Women's Lightweight Water-Resistant Hooded Puffer Coat",
    description: "Stay warm and dry in our hooded puffer jacket. Made with water-resistant taffeta fabric, it's fully lined, quilted, and insulated for extra protection on the coldest days. Features include a classic quilted pattern, front zipper closure, zip pockets, and elasticized cuffs. Perfect for layering in fall or winter. Easy-to-use 2-way zipper for added convenience",
    image: "https://m.media-amazon.com/images/I/71c5YUGsguL._AC_SX569_.jpg",
    price: 38.90,
    buyUrl: "https://www.amazon.com/Amazon-Essentials-Lightweight-Water-Resistant-Packable/dp/B07C8VG2F7/ref=sr_1_1_ffob_sspa?crid=7XMPLLJ6IV8G&keywords=womens+coat&qid=1707327175&sprefix=womans+coat%2Caps%2C137&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["womens","apparel","coat"],
  },
  {
    name: "Amazon Essentials Men's Packable Lightweight Water-Resistant Puffer Jacket",
    description: "Stay warm and stylish with our water-resistant puffer jacket. Made with nylon taffeta fabric, it's fully lined, quilted, and insulated for cold weather. Features include a full-length zipper, stand-up collar, zippered pockets, and elastic cuffs and bottom. Comes with a convenient carrying bag for easy storage.",
    image: "https://m.media-amazon.com/images/I/81UiEq+TM6L._AC_SX569_.jpg",
    price: 38.00,
    buyUrl: "https://www.amazon.com/Amazon-Essentials-Lightweight-Water-Resistant-Packable/dp/B07BN3XQ4R/ref=sr_1_6?crid=2HBOSGU29SC4J&keywords=mens%2Bcoat&qid=1707327334&sprefix=mens%2Bcoat%2Caps%2C145&sr=8-6&th=1&psc=1",
    keywords: ["mens","apparel","coat"],
  },
  {
    name: "Beaully Women's Flannel Plaid Shacket Long Sleeve Button Down Shirts Jacket Coats with Side Pockets",
    description: "Elevate your style with our high-quality flannel button-up shirt. Made from soft, wear-resistant fabric, it's perfect for autumn and winter. Features include a button front, plaid print, scoop hemline, and flap chest pockets. Wear it open as a jacket or closed as a shirt for a versatile look. Ideal for daily wear, outdoor activities, or casual outings.",
    image: "https://m.media-amazon.com/images/I/61LSELYQ26L._AC_SY741_.jpg",
    price: 32.89,
    buyUrl: "https://www.amazon.com/Beaully-Brushed-Flannel-Pocketed-Shacket/dp/B09H4G83H1/ref=sr_1_6?crid=35IJVTHQXVQU6&keywords=womens+shirt&qid=1707327486&sprefix=womans+shirt%2Caps%2C153&sr=8-6",
    keywords: ["womens","apparel","shirt"],
  },
  {
    name: "Legendary Whitetails Men's Buck Camp Flannel, Long Sleeve Plaid Button Down Casual Shirt, Corduroy Cuffs",
    description: "Elevate your style with our Buck Camp Flannel Shirt for men. Crafted from 100% soft brushed cotton flannel, it offers warmth and breathability for indoor and outdoor wear. With a relaxed fit and double-pleated back, it ensures comfort and ease of movement. The classic design features a single pocket with a pencil slot and corduroy-lined cuffs and collar for added durability and style. Enjoy immediate comfort and lasting quality wash after wash",
    image: "https://m.media-amazon.com/images/I/91yuQ3m+cvL._AC_SX679_.jpg",
    price: 34.99,
    buyUrl: "https://www.amazon.com/Legendary-Whitetails-Flannels-Cedarwood-X-Large/dp/B01K0ET87G/ref=sr_1_8?crid=3HK4U57LWWLQH&keywords=mens%2Bshirt&qid=1707327578&sprefix=mens%2Bshirt%2Caps%2C146&sr=8-8&th=1&psc=1",
    keywords: ["mens","apparel","shirt"],
  },
  {
    name: "Hey Dude Women's Wendy Chambray | Women's Shoes | Women's Lace Up Loafers | Comfortable & Light-Weight",
    description: "The Hey Dude Wendy shoes offer modern-casual style and comfort for women. With a rounded toe design and flex & fold feature, they support healthy feet and provide freedom of movement. Lightweight and equipped with elastic laces, they offer a uniform fit and weigh under 5 ounces each. Made from durable, high-quality material, they're perfect for women on the go and are machine washable for easy care. Backed by a 90-day manufacturer's warranty, you can shop with confidence.",
    image: "https://m.media-amazon.com/images/I/81hmrUHUTJL._AC_SY695_.jpg",
    price: 58.49,
    buyUrl: "https://www.amazon.com/Hey-Dude-Womens-Wendy-Stone/dp/B08DJ18MVN/ref=sr_1_2_sspa?crid=3880M4ZWV8QL7&keywords=womens+shoes&qid=1707327668&sprefix=womens+shoe%2Caps%2C144&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["womens","apparel","shoes"],
  },
  {
    name: "True Crime Case Histories",
    description:"Warning: This true crime collection dives deep into gruesome details, offering a raw look at the minds of killers. Not for the faint-hearted, these stories unveil the dark side of humanity, leaving nothing out. Brace yourself for a chilling exploration of the human psyche.",
    image: "https://m.media-amazon.com/images/I/71EBCyc0xBL._SY466_.jpg",
    price: 29.99,
    buyUrl: "https://www.amazon.com/True-Crime-Case-Histories-Disturbing/dp/1956566228/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326300&sr=8-2-spons",
    keywords: ["crime","book", "reading"],
  },
  {
    name: "Icebreaker: A Novel",
    description:"Figure skater Ana dreams of Team USA. But a twist of fate lands her on the same ice as hockey captain Nate. Sparks fly, but with Ana's future at stake, she might need Nate's help. Can love thaw their icy relationship?",
    image: "https://m.media-amazon.com/images/I/71nKtAPngQL._SY466_.jpg",
    price: 11.32,
    buyUrl: "https://www.amazon.com/Icebreaker-Novel-Maple-Hannah-Grace/dp/1668026031/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1707326450&sr=8-7",
    keywords: ["romantic","book", "reading"],
  },
  {
    name: "A Court of Thorns and Roses",
    description: "When huntress Feyre kills a wolf, she's taken to a magical realm by a faerie. But he's not just a beast—he's Tamlin, a lethal immortal. As Feyre's icy feelings thaw into passion, she uncovers a dark threat looming over the faerie lands. Can she save Tamlin's world before it's too late?",
    image: "https://m.media-amazon.com/images/I/81LftCZRUML._SY466_.jpg",
    price: 17.59,
    buyUrl: "https://www.amazon.com/Court-Thorns-Roses-Sarah-Maas/dp/1635575559/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326623&sr=8-6",
    keywords: ["fantasy","book", "reading"],
  },
  {
    name: "Hidden Pictures: A Novel",
    description: "Fresh out of rehab, Mallory becomes a nanny for Teddy, a sweet boy with a disturbing secret. His drawings hint at a sinister past, leading Mallory into a supernatural mystery. Can she unravel the truth before it's too late?",
    image: "https://m.media-amazon.com/images/I/91puw8POkwL._SY466_.jpg",
    price: 14.73,
    buyUrl: "https://www.amazon.com/Hidden-Pictures-Novel-Jason-Rekulak/dp/1250819342/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326722&sr=8-6",
    keywords: ["horror","book", "reading"],
  },
  {
    name: "An Innocent Client: A Legal Thriller",
    description: "A preacher's murder in a Tennessee motel implicates a mysterious young girl. Criminal defense lawyer Joe Dillard, despite personal struggles, takes on her case, torn between career and conscience. Rich characters and a surprising plot twist mark this debut novel, leaving readers eager for more.",
    image: "https://m.media-amazon.com/images/I/51zSDpDOibL._SY445_SX342_.jpg",
    price: 24.99,
    buyUrl: "https://www.amazon.com/Innocent-Client-Legal-Thriller-Dillard/dp/1944083103/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707326866&sr=8-3-spons",
    keywords: ["mystery","book", "reading"],
  },
  {
    name: "Dragons Love Farts: They're More Fun Than Tacos!",
    description: "Get ready for a laugh-out-loud adventure with Dragons Love Farts! Packed with hilarious memes and silly dragons, this book is perfect for kids who love to giggle. From historical events like Woodstock to literary nods and bedtime stories, Dragons Love Farts is sure to entertain kids again and again. It's the ultimate funny book for boys aged 4-6 or kids aged 5-7, with rhymes reminiscent of Dr. Seuss and illustrations that spark curiosity. Don't miss out on the fun - grab your copy today! 🐉💨",
    image: "https://m.media-amazon.com/images/I/619ZUIo+baL._SY466_.jpg",
    price: 12.35,
    buyUrl: "https://www.amazon.com/Dragons-Love-Farts-Theyre-Tacos/dp/1951696077/ref=sr_1_1_sspa?crid=1R16U8VIEDHAQ&keywords=kid+book&qid=1707326983&sprefix=kid+book%2Caps%2C140&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["child","book","reading","childrens"],
  },
  {
    name: "Samsung 98-Inch Neo QLED 4k Smart TV",
    description:
      "The Samsung QN90A Smart TV delivers stunning picture quality with Quantum HDR 32X and Quantum Matrix Technology, providing vibrant colors and impeccable contrast. Experience immersive sound with Object Tracking Sound+ technology, while the Ultra Viewing Angle ensures optimal viewing from any seat.",
    image: "https://m.media-amazon.com/images/I/913+l9CB6cL._AC_SX679_.jpg",
    price: 9997.99,
    buyUrl:
      "https://www.amazon.com/SAMSUNG-98-Inch-Quantum-Tracking-QN98QN90AAFXZA/dp/B097FDNQ69/ref=sr_1_3?crid=ED7H232QXR29&keywords=tv+expensive&qid=1707324960&sprefix=tv+expensive%2Caps%2C137&sr=8-3&ufe=app_do%3Aamzn1.fos.17f26c18-b61b-4ce9-8a28-de351f41cffb",
    keywords: ["expensive", "tech", "tv"],
  },
  {
    name: "LG 50-Inch 4k Smart TV",
    description:
      "The LG 4K UHD TV offers a smart viewing experience with access to 300+ free LG Channels and FILMMAKER MODE for cinematic visuals. Enjoy HDR10 Pro for vibrant contrast and AI-powered upscaling to 4K. With LG webOS 23, find your favorite apps easily with Quick Cards and enhance your gaming experience with LG Game Optimizer and GeForce NOW.",
    image: "https://m.media-amazon.com/images/I/91MAjR2HydL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    price: 396.99,
    buyUrl: "https://www.amazon.com/LG-50-Inch-Bluetooth-Ethernet-AI-Powered/dp/B0BVXDQYQB/ref=sr_1_10?crid=1BKSGITXYSE9H&keywords=tv%2Bmid%2Brange&qid=1707325735&sprefix=tv%2Bmid%2Brange%2Caps%2C149&sr=8-10&ufe=app_do%3Aamzn1.fos.c3015c4a-46bb-44b9-81a4-dc28e6d374b3&th=1",
    keywords: ["affordable","tech","tv"],
  },
  {
    name: "Amazon Fire TV 32-Inch Smart TV",
    description: "The Fire TV 2-Series offers brilliant 720p HD resolution with HDR 10 support and Dolby Digital Audio. Access 1 million movies and TV episodes, with 200,000 available for free, from any room in your home. Use the Fire TV Alexa Voice Remote for easy navigation and control of your entertainment and smart home devices",
    image: "https://m.media-amazon.com/images/I/418UoVylqyL._AC_SY450_.jpg",
    price: 119.99,
    buyUrl: "https://www.amazon.com/introducing-amazon-fire-tv-32-inch-2-series-hd-smart-tv/dp/B09N6F9NV3/ref=sr_1_4?crid=1J1PVDG3Z5G8&keywords=tv%2Bcheap&qid=1707325364&sprefix=tv%2Bcheap%2Caps%2C161&sr=8-4&th=1",
    keywords: ["cheap","tech","tv"],
  },
  {
    name: "Amazon Essentials Women's Lightweight Water-Resistant Hooded Puffer Coat",
    description: "Stay warm and dry in our hooded puffer jacket. Made with water-resistant taffeta fabric, it's fully lined, quilted, and insulated for extra protection on the coldest days. Features include a classic quilted pattern, front zipper closure, zip pockets, and elasticized cuffs. Perfect for layering in fall or winter. Easy-to-use 2-way zipper for added convenience",
    image: "https://m.media-amazon.com/images/I/71c5YUGsguL._AC_SX569_.jpg",
    price: 38.90,
    buyUrl: "https://www.amazon.com/Amazon-Essentials-Lightweight-Water-Resistant-Packable/dp/B07C8VG2F7/ref=sr_1_1_ffob_sspa?crid=7XMPLLJ6IV8G&keywords=womens+coat&qid=1707327175&sprefix=womans+coat%2Caps%2C137&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["womens","apparel","coat"],
  },
  {
    name: "Amazon Essentials Men's Packable Lightweight Water-Resistant Puffer Jacket",
    description: "Stay warm and stylish with our water-resistant puffer jacket. Made with nylon taffeta fabric, it's fully lined, quilted, and insulated for cold weather. Features include a full-length zipper, stand-up collar, zippered pockets, and elastic cuffs and bottom. Comes with a convenient carrying bag for easy storage.",
    image: "https://m.media-amazon.com/images/I/81UiEq+TM6L._AC_SX569_.jpg",
    price: 38.00,
    buyUrl: "https://www.amazon.com/Amazon-Essentials-Lightweight-Water-Resistant-Packable/dp/B07BN3XQ4R/ref=sr_1_6?crid=2HBOSGU29SC4J&keywords=mens%2Bcoat&qid=1707327334&sprefix=mens%2Bcoat%2Caps%2C145&sr=8-6&th=1&psc=1",
    keywords: ["mens","apparel","coat"],
  },
  {
    name: "Beaully Women's Flannel Plaid Shacket Long Sleeve Button Down Shirts Jacket Coats with Side Pockets",
    description: "Elevate your style with our high-quality flannel button-up shirt. Made from soft, wear-resistant fabric, it's perfect for autumn and winter. Features include a button front, plaid print, scoop hemline, and flap chest pockets. Wear it open as a jacket or closed as a shirt for a versatile look. Ideal for daily wear, outdoor activities, or casual outings.",
    image: "https://m.media-amazon.com/images/I/61LSELYQ26L._AC_SY741_.jpg",
    price: 32.89,
    buyUrl: "https://www.amazon.com/Beaully-Brushed-Flannel-Pocketed-Shacket/dp/B09H4G83H1/ref=sr_1_6?crid=35IJVTHQXVQU6&keywords=womens+shirt&qid=1707327486&sprefix=womans+shirt%2Caps%2C153&sr=8-6",
    keywords: ["womens","apparel","shirt"],
  },
  {
    name: "Legendary Whitetails Men's Buck Camp Flannel, Long Sleeve Plaid Button Down Casual Shirt, Corduroy Cuffs",
    description: "Elevate your style with our Buck Camp Flannel Shirt for men. Crafted from 100% soft brushed cotton flannel, it offers warmth and breathability for indoor and outdoor wear. With a relaxed fit and double-pleated back, it ensures comfort and ease of movement. The classic design features a single pocket with a pencil slot and corduroy-lined cuffs and collar for added durability and style. Enjoy immediate comfort and lasting quality wash after wash",
    image: "https://m.media-amazon.com/images/I/91yuQ3m+cvL._AC_SX679_.jpg",
    price: 34.99,
    buyUrl: "https://www.amazon.com/Legendary-Whitetails-Flannels-Cedarwood-X-Large/dp/B01K0ET87G/ref=sr_1_8?crid=3HK4U57LWWLQH&keywords=mens%2Bshirt&qid=1707327578&sprefix=mens%2Bshirt%2Caps%2C146&sr=8-8&th=1&psc=1",
    keywords: ["mens","apparel","shirt"],
  },
  {
    name: "Hey Dude Women's Wendy Chambray | Women's Shoes | Women's Lace Up Loafers | Comfortable & Light-Weight",
    description: "The Hey Dude Wendy shoes offer modern-casual style and comfort for women. With a rounded toe design and flex & fold feature, they support healthy feet and provide freedom of movement. Lightweight and equipped with elastic laces, they offer a uniform fit and weigh under 5 ounces each. Made from durable, high-quality material, they're perfect for women on the go and are machine washable for easy care. Backed by a 90-day manufacturer's warranty, you can shop with confidence.",
    image: "https://m.media-amazon.com/images/I/81hmrUHUTJL._AC_SY695_.jpg",
    price: 58.49,
    buyUrl: "https://www.amazon.com/Hey-Dude-Womens-Wendy-Stone/dp/B08DJ18MVN/ref=sr_1_2_sspa?crid=3880M4ZWV8QL7&keywords=womens+shoes&qid=1707327668&sprefix=womens+shoe%2Caps%2C144&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["womens","apparel","shoes"],
  },
  
  {
    name: "OREO Chocolate Sandwich Cookies, Holiday Cookies, 12 - 4 oz Stocking Stuffer Packs",
    description: "Enjoy the holiday season with twelve 4 oz packs of OREO Chocolate Sandwich Cookies, perfect for stocking stuffers or holiday gifts. Made with original creme filling between chocolate wafers and 100% Sustainably Sourced Cocoa, these kosher snacks are a thoughtful treat for teachers, friends, family, or neighbors. Individual packs in festive holiday packaging make them ideal stocking stuffer ideas or holiday party favors.",
    image: "https://m.media-amazon.com/images/I/818+tVvvCRL._SX679_.jpg",
    price: 18.19,
    buyUrl: "https://www.amazon.com/OREO-Chocolate-Sandwich-Cookies-Christmas/dp/B08HT9NBLL/ref=sr_1_6?crid=MWUVAG5UBZPV&keywords=snacks+christmas&qid=1707336955&rdc=1&sprefix=snacks+christmas%2Caps%2C293&sr=8-6",
    keywords: ["snacks", "christmas"],
  },
  {
    name: "Homsolver Gifts for Mom from Daughter Son, Best Mom Gifts, Funny Mom Christmas Gifts, Birthday Thanksgiving Mothers Day Gifts for Mom Stepmother Adoptive Mother, Mom's Last Nerve",
    description: "Express your love for Mom with this funny and heartwarming lavender-scented candle, perfect for any occasion. Made from 100% natural soy wax, it lasts up to 50 hours, offering a calming lavender aroma that promotes relaxation and better sleep quality.",
    image: "https://m.media-amazon.com/images/I/61cmyzcgBlL._AC_SX679_.jpg",
    price: 9.99,
    buyUrl: "https://www.amazon.com/Mothers-Daughter-Birthday-Christmas-Nerve-Pink/dp/B0BR41SJYD/ref=sr_1_10?crid=9BFYJ6KEI7A0&keywords=mothers%2Bday%2Bgifts&qid=1707338919&sprefix=mothers%2Bday%2Bgifts%2Caps%2C144&sr=8-10&th=1",
    keywords: ["mother","wellness"],
  },
  {
    name: "Men's Customizable Dad Belongs to Your Kids Names T-Shirt | Father's Day Custom Tee",
    description: "Discover premium quality graphic tees perfect for every style and occasion from Silver Lake T-shirts. Made in the USA with top-notch materials, our shirts offer a soft, worn-in feel and are available in a wide range of sizes. Whether you're shopping for a special gift or want to make a statement with unique designs, our collection has something for everyone.",
    image: "https://m.media-amazon.com/images/I/81rEtwdX7mL._AC_SX679_.jpg",
    price: 21.99,
    buyUrl: "https://www.amazon.com/Customizable-Belongs-T-Shirt-Fathers-3X-Large/dp/B0B6D7M4L7/ref=sr_1_22_sspa?crid=35NGUK4XUTJGV&keywords=fathers+day+gifts&qid=1707339134&sprefix=fathers+day+gifts%2Caps%2C135&sr=8-22-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1",
    keywords: ["father","apparel"],
  },
  {
    name: "Paint & Plant Flower Growing Kit for Kids - Best Birthday Crafts Gifts for Girls & Boys Age 5 6 7 8-12 Year Old Girl Gift Ideas - Fun Children Gardening Kits, Art Projects Toys for Ages 5-12 Years",
    description: "Engage in creative gardening with our Paint & Plant Kit, featuring Marigold, Cosmos, and Zinnia flowers. Enjoy painting the planter and markers to make it uniquely yours. Perfect for all ages, this kit includes everything needed for a fun and educational experience, teaching kids about plant lifecycles and fostering creativity.",
    image: "https://m.media-amazon.com/images/I/91j3V70TAvL._AC_SX466_.jpg",
    price: 19.99,
    buyUrl: "https://www.amazon.com/Dan-Darci-Paint-Flower-Growing/dp/B07KQLCGSR/ref=sr_1_8?crid=V2D7F2VD00CB&keywords=easter+gift&qid=1707339328&sprefix=easter+gift%2Caps%2C131&sr=8-8",
    keywords: ["easter","child","gardening"],
  },
  {
    name: "Caramella Bubble Bunny Slippers for Women Fuzzy Cute Animal Memory Foam Indoor House Slippers Easter Thanksgiving Christmas Slippers Gifts",
    description: "For those with wider feet, consider going up one size for optimal fit. Our slippers offer ultimate comfort with a thick wool-like upper and cozy lining, providing a cloud-like walking experience. Featuring a durable rubber sole, they're suitable for both indoor and outdoor use. These slippers make a warm and thoughtful gift for Christmas, New Year, or as a pregnancy present. Please handwash gently to maintain their cute appearance and longevity.",
    image: "https://m.media-amazon.com/images/I/61wwpiRE1WL._AC_SY575_.jpg",
    price: 19.99,
    buyUrl: "https://www.amazon.com/Slippers-Womens-Memory-Bedroom-Outdoor/dp/B07H895K7Q/ref=sr_1_7?crid=365B4YG4GCNZU&keywords=easter%2Badult%2Bgift&qid=1707339402&sprefix=easter%2Badult%2Bgif%2Caps%2C124&sr=8-7&th=1&psc=1",
    keywords: ["easter","adult","womens","apparel","pink"],
  },
  {
    name: "Amazon.com Gift Card in a Congratulations or Graduation Style Gift Box (Various Designs)",
    description: "Get that graduate the gift of $$$. Chose from values of as low as $25 or as high as $2000. Nothing says 'Well done,' like an investment in them.",
    image: "https://m.media-amazon.com/images/I/71U87mzDDaL._SX522_.jpg",
    price: 25.00,
    buyUrl: "https://www.amazon.com/Amazon-com-Gift-Card-Graduation-Cap/dp/B01N9GY4GF/ref=sr_1_5?crid=IVNLYI1ES83H&keywords=graduation%2Bgifts&qid=1707339529&sprefix=graduation%2Bgifts%2Caps%2C128&sr=8-5&th=1",
    keywords: ["graduation"],
  },
  {
    name: "Larchio Graduation Gifts for Her- Graduation Gifts Graduation Coffee Mug Set",
    description: "Celebrate her graduation with the Congrats Grad! Gift Set, featuring a shiny graduation mug, inspirational keychain, scented candle, fluffy bear cloth, dried flower bouquet, and greeting card—all wrapped up and ready to go. This thoughtful gift encapsulates her achievements and offers daily moments of relaxation and inspiration.",
    image: "https://m.media-amazon.com/images/I/71fRAxl+v8L._AC_SX679_.jpg",
    price: 16.99,
    buyUrl: "https://www.amazon.com/Larchio-Graduation-Keychain-Daughter-Granddaughter/dp/B0BS6HW7KT/ref=sr_1_9?crid=IVNLYI1ES83H&keywords=graduation%2Bgifts&qid=1707339657&sprefix=graduation%2Bgifts%2Caps%2C128&sr=8-9&th=1",
    keywords: ["graduation","womens"],
  },
  {
    name: "Btysun Inspirational Gifts for Men Morse Code Bracelets Mens Bracelets Birthday Annivesary Gifts Graduation Leather Jewelry",
    description: "Make his graduation memorable with the Morse code bracelet, a durable and adjustable leather piece perfect for high school or college grads in 2024. Crafted to last, it's a versatile gift for birthdays, graduations, or any special occasion, complete with a gift box and friendly service.",
    image: "https://m.media-amazon.com/images/I/81R3-eDtNsL._AC_SY535_.jpg",
    price: 13.59,
    buyUrl: "https://www.amazon.com/Graduation-Bracelets-Boyfriend-Classmate-Congratulate/dp/B0BVM3SD6J/ref=sr_1_2?crid=2YZYM9RZCZ4SI&keywords=graduation%2Bmens&qid=1707339799&sprefix=graduation%2Bmens%2Caps%2C129&sr=8-2&th=1",
    keywords: ["graduation", "mens"],
  },
  {
    name: "LANDNEOO 4pcs Set Vintage Coffee Mugs, Overnight Oats Containers with Bamboo Lids and Spoons - 14oz Clear Embossed Glass Cups, Cute Coffee Bar Accessories, Iced Coffee Glasses",
    description: "Enhance your dining experience with this elegant vintage coffee mug set, featuring 4 crystal glass mugs—2 embossed with sunflower patterns and 2 with raindrops patterns—along with rose-gold spoons and bamboo lids. With a charming blend of retro aesthetics and practicality, these lead-free, durable mugs hold 14oz and make an ideal gift for any occasion, securely boxed for gifting success.",
    image: "https://m.media-amazon.com/images/I/81HGpJbrnaL._AC_SX679_.jpg",
    price: 19.99,
    buyUrl: "https://www.amazon.com/Vintage-Coffee-Overnight-Containers-Bamboo/dp/B0BM9LPS47/ref=sr_1_6?crid=9OFUW31UM7BX&keywords=housewarming%2Bgifts&qid=1707339881&sprefix=housewarming%2Bgift%2Caps%2C138&sr=8-6&th=1",
    keywords: ["housewarming", "kitchen"],
  },
  {
    name: "XXXFLOWER Plant Terrarium with Wooden Stand, Air Planter Bulb Glass Vase Metal Swivel Holder Retro Tabletop for Hydroponics Home Garden Office Decoration - 3 Bulb Vase",
    description: "Elevate your décor with this vintage-inspired terrarium set, featuring three bulb-shaped glass vases on a sturdy natural wood frame. Perfect for displaying colored water, stones, flowers, or plants, it adds a touch of elegance to any space. Ideal for plant lovers, it makes a thoughtful gift for various occasions, complete with easy setup instructions.",
    image: "https://m.media-amazon.com/images/I/71GrAWYYDyL._AC_SX679_.jpg",
    price: 19.98,
    buyUrl: "https://www.amazon.com/Terrarium-Planter-Tabletop-Hydroponics-Decoration/dp/B07D29P5Z1/ref=sr_1_15?crid=9OFUW31UM7BX&keywords=housewarming+gifts&qid=1707339987&sprefix=housewarming+gift%2Caps%2C138&sr=8-15",
    keywords: ["housewarming","gardening"],
  },
  {
    name: "Luna Bean Hand Casting Kit - Unique Couples Gifts for Christmas, Anniversaries, Bridal Showers, Weddings, Engagements, Grandma - Mold Kit for Her, Him",
    description: "Capture a special moment with your loved one using our Couples Hand Casting Kit, an ideal gift for couples, anniversaries, or Christmas. With premium materials for detailed results, our kit offers more molding materials and guarantees satisfaction with our keepsake guarantee. Includes everything needed for a fun and easy casting experience.",
    image: "https://m.media-amazon.com/images/I/81QCGcHXW3L._AC_SX466_.jpg",
    price: 39.98,
    buyUrl: "https://www.amazon.com/Luna-Bean-KEEPSAKE-Plaster-Materials/dp/B01E4LWBLQ/ref=sr_1_2_sspa?crid=3LFT98R9QAUWT&keywords=anniversary%2Bgifts&qid=1707340106&sprefix=anniversary%2Bgift%2Caps%2C130&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    keywords: ["anniversary","mens","womens","romantic"],
  },
  {
    name: "Him Her Couple Gifts for Boyfriend Girlfriend Food Decider 11th Anniversary Steel Date Night Gifts for Husband Wife for Wedding Christmas Valentines Birthday for Women Men",
    description: "Take the guesswork out of date night with our Funny Food Decision Dice, perfect for couples celebrating anniversaries, Valentine's Day, or Christmas. Made of stainless steel, it's a playful yet practical gift for any occasion, helping to solve the eternal question of 'What's for dinner?'. With engraved food choices, it's a humorous and thoughtful present for birthdays, anniversaries, or any special day.",
    image: "https://m.media-amazon.com/images/I/61za2zzTPIL._AC_SX466_.jpg",
    price: 13.99,
    buyUrl: "https://www.amazon.com/Anniversary-Boyfriend-Girlfriend-Christmas-Valentines/dp/B0C5LRR1ZY/ref=sr_1_7?crid=3LFT98R9QAUWT&keywords=anniversary%2Bgifts&qid=1707340179&sprefix=anniversary%2Bgift%2Caps%2C130&sr=8-7&th=1",
    keywords: ["anniversary","mens","womens","romantic","toy"],
  },
  {
    name: "CENSIHER Gift for Wife from Husband to My Wife Blanket Wedding Anniversary Romantic Gifts for Wife Birthday Christmas Valentine's Mother's Day Healing Thoughts Blanket Presents for Her",
    description: "Wrap your loved ones in comfort and encouragement with our super soft Flannel blanket, featuring uplifting blessings and positive affirmations. Perfect for those facing challenges, illness, or in need of spiritual support, this high-quality blanket promotes positive thinking and warmth. Machine washable and durable, it's a thoughtful gift to bring comfort and positivity during difficult times, measuring 65x50 inches and made of 100% microfiber polyester.",
    image: "https://m.media-amazon.com/images/I/81r7JoU9hEL._AC_SX679_.jpg",
    price: 38.99,
    buyUrl: "https://www.amazon.com/Anniversary-Romantic-Birthday-Christmas-Valentines/dp/B09833TQPB/ref=sr_1_6?crid=3R709QFJ8RA39&keywords=anniversary%2Bgifts%2Bfor%2Bher&qid=1707340255&sprefix=anniversary%2Bgifts%2Bfor%2Bher%2Caps%2C123&sr=8-6&th=1",
    keywords: ["womens", "anniversary","mother", "christmas","valentines","wellness"],
  },
  {
    name: "Fanfoobi Husband Birthday Present, Pocket Knife with 6 Functions, LED Light,Fire Starter,Bottle Opener,Seat Belt Cutter,Glass Breaker, Anniversary Present for Men, Boyfriend, Father's Day",
    description: "Multi-functional 8-inch tool featuring LED light, fire starter, bottle opener, seat belt cutter, glass breaker, and cutting capabilities, perfect for outdoor and emergency use, with a wooden handle making it an ideal gift for men on various occasions.",
    image: "https://m.media-amazon.com/images/I/51r1-D4LecL._AC_SX679_.jpg",
    price: 18.99,
    buyUrl: "https://www.amazon.com/Husband-Birthday-Functions-Starter-Boyfriend/dp/B07NVLBK3B/ref=sr_1_7?crid=F0CE999MDW5A&keywords=anniversary%2Bgifts%2Bfor%2Bhim&qid=1707340513&sprefix=anniversary%2Bgifts%2Bfor%2Bhim%2Caps%2C128&sr=8-7&th=1",
    keywords: ["father","mens","anniversary","romantic","birthday"],
  },
  {
    name: "Witches Brew Cauldron Mug",
    description: "Indulge in the mystical charm of this cauldron-designed 'Witches Brew' mug, featuring a moon and stars motif, packaged in a matching box, and suitable for both left and right-handed users. Dishwasher and microwave safe, it makes an enchanting gift for any occasion",
    image: "https://m.media-amazon.com/images/I/518bkMT3WAL._AC_SX679_.jpg",
    price: 9.75,
    buyUrl: "https://www.amazon.com/Something-different-Witches-Brew-Cauldron/dp/B07K2HLD3W/ref=sr_1_5?crid=1APZ7XGQOH1&keywords=halloween+gifts&qid=1707340654&sprefix=halloween+gifts%2Caps%2C129&sr=8-5",
    keywords: ["halloween","kitchen","cheap"],
  },
  {
    name: "8Pcs Horror Classic Movie Character Car Air Fresheners Gift Set Halloween Incense Chips Scented Car Diffuser Rearview Mirror Hanging Pendant Ornaments Decor Automotive Interior Accessories Party Favor",
    description: "Elevate your car or home ambiance with our Halloween Horror Movie Themed Car Air Freshener, featuring 8 packs of fragrance chips inspired by classic scary characters. Made of high-quality materials, these durable chips offer long-lasting freshness, perfect for any occasion or Halloween party. Plus, our dedicated customer service team ensures a seamless experience for you.",
    image: "https://m.media-amazon.com/images/I/81C7LCGIXfL._AC_SX679_PIbundle-8,TopRight,0,0_SH20_.jpg",
    price: 9.99,
    buyUrl: "https://www.amazon.com/Character-Fresheners-Halloween-Ornaments-Automotive/dp/B0BCFXR87B/ref=sr_1_8?crid=1APZ7XGQOH1&keywords=halloween+gifts&qid=1707340734&sprefix=halloween+gifts%2Caps%2C129&sr=8-8",
    keywords: ["halloween","cheap"],
  },
  
  {
    name: "Childom Valentines Day Gifts for Her,Birthday Gifts for Women,Artificial Preserved Flowers,Valentines Gifts for Mom Wife Girlfriend Grandma,Valentines Colorful Rainbow Light Up Rose in A Glass Dome",
    description: "Surprise her with this romantic Rainbow Valentines Rose Flowers Gift in a Glass Dome, perfect for Valentine's Day, birthdays, or any special occasion. Featuring LED lighting and a variety of vibrant colors, this preserved flower gift is sure to bring endless joy and romance to her day.",
    image: "https://m.media-amazon.com/images/I/71y2BOA8fbL._AC_SX679_.jpg",
    price: 17.99,
    buyUrl: "https://www.amazon.com/Colorful-Artificial-Christmas-Valentines-Anniversary/dp/B07ZR8RRX5?ref_=ast_sto_dp&th=1",
    keywords: ["romantic","womens","anniversary","birthday","mother"],
  },
  {
    name: "BEARD KING Beard Bib Apron - Shaving Set for Dad - As Seen on Shark Tank - Men's Hair Catcher for Shaving - Grooming Accessories, Black.",
    description: "Conquer shaving messes with ease using our Beard Hair Catcher, featuring mirror suction cups for effortless setup and cleanup. Keep your bathroom clean and clog-free while protecting your chest, neck, and shoulders. As seen on Shark Tank, this beard apron is the perfect gift for any man tired of messy shaves.",
    image: "https://m.media-amazon.com/images/I/71tLhddle0L._SY879_.jpg",
    price: 15.49,
    buyUrl: "https://www.amazon.com/beard-bib-shaving-trimmer-catcher-net/dp/B07HGJTHY3/ref=sr_1_28?crid=39IS6C858N8MC&keywords=birthday+gifts+for+men&qid=1707340896&sprefix=birthday+gifts%2Caps%2C128&sr=8-28",
    keywords: ["mens","birthday","father"],
  },
  {
    name: "Catalonia Oversized Blanket Hoodie Sweatshirt, Wearable Sherpa Lounging Pullover for Adults Women Men",
    description: "Stay cozy and warm with our versatile blanket sweatshirt, perfect for gifting on various occasions. Enjoy its soft Sherpa and micro smooth fleece materials, oversized design, and convenient front pocket for hands and personal items. Suitable for all ages and backed by a worry-free replacement policy",
    image: "https://m.media-amazon.com/images/I/81xSD6LtG2L._AC_SY741_.jpg",
    price: 39.99,
    buyUrl: "https://www.amazon.com/Catalonia-Oversized-Sweatshirt-Blanket-Comfortable/dp/B07JHN1Y7W/ref=sr_1_6?crid=3918JSPG13KF&keywords=general+gifts&qid=1707341153&sprefix=general+gifts%2Caps%2C156&sr=8-6",
    keywords: ["general","mens","womens","apparel"],
  },
  {
    name: "Portable Charger Power Bank 25800mAh, Ultra-High Capacity Fast Phone Charging with Newest Intelligent Controlling IC, 2 USB Port External Cell Phone Battery Pack Compatible with iPhone,Android etc",
    description: "Stay powered up with our latest design portable charger featuring a 25800mAh ultra-huge capacity, dual USB charging, and universal compatibility. With fast recharge capabilities and certified safety features, it's perfect for travel and outdoor activities. Includes 24 months of support services for peace of mind.",
    image: "https://m.media-amazon.com/images/I/612vaudnEkL._AC_SX679_.jpg",
    price: 25.95,
    buyUrl: "https://www.amazon.com/Portable-25800mAh-Ultra-High-Intelligent-Controlling/dp/B07XQ94ZL9/ref=sr_1_1_sspa?crid=2FCJGX7JWRMX0&keywords=portable%2B25800mah%2Bultra%2Bhigh%2Bintelligent&qid=1707350207&sprefix=portalbe%2B25800mah%2Bultra%2Bhigh%2Bintelligent%2Caps%2C116&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&smid=A17V99AE1N6ZHR&th=1",
    keywords: ["general","adult"],
  },
  {
    name: "OLsky Massage Gun Deep Tissue, Handheld Electric Muscle Massager, High Intensity Percussion Massage Device for Pain Relief with 9 Attachments & 30 Speed(Grey)",
    description: "Experience relaxation and recovery with the Olsky deep tissue massage gun, featuring 9 massage heads, 30-speed levels, and an ergonomic design for targeted relief in various muscle groups. With a rechargeable battery and smart LED display, enjoy powerful yet quiet operation anywhere, anytime.",
    image: "https://m.media-amazon.com/images/I/6186oc3mpvL._AC_SX679_.jpg",
    price: 25.99,
    buyUrl: "https://www.amazon.com/Handheld-Electric-Intensity-Percussion-Attachments/dp/B08TLWYKLS/ref=sr_1_26?crid=P1OK28OGVAQS&keywords=adult%2Bgifts&qid=1707341318&sprefix=adult%2Bgift%2Caps%2C127&sr=8-26&th=1",
    keywords: ["general","adult","wellness","bedroom"],
  },
  {
    name: "Homedics Tabletop Water Fountain, Home Décor Soothing Sound Machine - Automatic Pump, Deep Basin & Natural River Rocks. Indoor Zen Relaxation for Office, Living Room, or Bedroom, 8.25” Tall",
    description: "Create a tranquil ambiance with our Decorative Tabletop Fountain, featuring a 3-tier design for soothing water flow, an easy-to-use built-in pump, and an artistic Asian-inspired aesthetic. Perfect for relaxation, meditation, or as a night-light in a baby's nursery, it comes with river rocks and a convenient power cord and adapter.",
    image: "https://m.media-amazon.com/images/I/815vZaQ9FXL._AC_SX679_.jpg",
    price: 29.99,
    buyUrl: "https://www.amazon.com/Homedics-Tabletop-Water-Fountain-Soothing/dp/B000QTUJXS/ref=sr_1_1_sspa?crid=3B8EUTITJLCQ&keywords=living+room+gifts&qid=1707341506&sprefix=living+room+gift%2Caps%2C135&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["living-room","wellness"],
  },
  {
    name: "Set of 5 Mesh Laundry Bags-1 Extra Large, 2 Large & Medium for Blouse, Hosiery, Stocking, Underwear, Bra Lingerie, Travel",
    description: "Keep your delicates protected and organized with our set of 5 Mesh Laundry Bags, featuring various sizes for different garments. Made of durable and breathable polyester fiber, these bags are perfect for laundry, travel, and dryer use. The premium mesh material ensures your clothes stay safe and extend their lifespan, while the see-through design makes it easy to find items and breeze through airport security checks.",
    image: "https://m.media-amazon.com/images/I/61Fy7sJ5yrL._AC_SX679_PIbundle-5,TopRight,0,0_SH20_.jpg",
    price: 7.99,
    buyUrl: "https://www.amazon.com/Laundry-Hosiery-Stocking-Underwear-Lingerie/dp/B017NEYOQQ/ref=sxin_14_pa_sp_search_thematic_sspa?content-id=amzn1.sym.92181fe7-c843-4c1b-b489-84c087a93895%3Aamzn1.sym.92181fe7-c843-4c1b-b489-84c087a93895&crid=L1I2PCBOG7U1&cv_ct_cx=laundry%2Broom%2Bgifts&keywords=laundry%2Broom%2Bgifts&pd_rd_i=B017NEYOQQ&pd_rd_r=fbe125e0-db23-48af-bf50-9a65fbf798b2&pd_rd_w=nTQg5&pd_rd_wg=vEkB0&pf_rd_p=92181fe7-c843-4c1b-b489-84c087a93895&pf_rd_r=MR2PJF3WE3D1V0F1860N&qid=1707341623&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=laundry%2Broom%2Bgift%2Caps%2C138&sr=1-1-364cf978-ce2a-480a-9bb0-bdb96faa0f61-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1",
    keywords: ["laundry","general"],
  },
  {
    name: "EVA murmure Cutout Letters Lost Socks - Laundry Room Organization, Farmhouse Laundry Room Decor And Accessories - House Decor Rustic Wooden Laundry Sign Wall Decor With Attached Basket - black",
    description: "Add a touch of humor and functionality to your laundry room with our 'Lost Socks Seeking Solemates' sign and basket set. Perfect for organizing those single socks and making a fun statement, it's also a great gift for moms, friends, and more. Easy to assemble and featuring a charming country-style design, it's the perfect addition to any rustic or farmhouse-themed laundry decor.",
    image: "https://m.media-amazon.com/images/I/715qjoTP15L._AC_SX679_.jpg",
    price: 29.99,
    buyUrl: "https://www.amazon.com/EVA-murmure-Cutout-Letters-Socks/dp/B098PJ97L7/ref=sr_1_33?crid=L1I2PCBOG7U1&keywords=laundry%2Broom%2Bgifts&qid=1707341623&sprefix=laundry%2Broom%2Bgift%2Caps%2C138&sr=8-33&th=1",
    keywords: ["laundry","black"],
  },
  {
    name: "Seatcraft Colosseum Leather 7000 Big & Tall - 400 lb Capacity Home Theater Furniture | Power Headrest, Power Lumbar, Power Recline (Sofa with Fold-Down Table & Loveseat with Storage Console, Black)",
    description: "Crafted from the finest top grain leather, this sofa and loveseat set offers unparalleled comfort and durability. With adjustable powered headrest, lumbar support, and recline features, along with convenient amenities like USB charging slots, stainless steel cupholders, and armrest storage, it's the perfect choice for luxury home theater experiences. Plus, shop with confidence knowing that Seatcraft, the top-rated brand on Amazon, ensures safe shipping and decades of industry-leading innovation.",
    image: "https://m.media-amazon.com/images/I/61hBo7rTZGL._AC_SX679_.jpg",
    price: 5772.80,
    buyUrl: "https://www.amazon.com/Seatcraft-Colosseum-Leather-7000-Tall/dp/B0BL8HDN96/ref=sr_1_11_sspa?crid=2MRRX1J8QD7MA&keywords=living+room+couch&qid=1707341778&sprefix=living+room+couch%2Caps%2C131&sr=8-11-spons&ufe=app_do%3Aamzn1.fos.17f26c18-b61b-4ce9-8a28-de351f41cffb&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1",
    keywords: ["living-room","expensive"],
  },
  {
    name: "How to Catch a Dinosaur",
    description: "Join the daring How to Catch Kids on a dinomite adventure as they attempt to wrangle a dinosaur for the school science fair! Packed with laughter, STEAM concepts, and clever chaos, this picture book is perfect for dinosaur fans ages 4-10. Discover if YOU have what it takes to pluck a prehistoric pal and don't miss other titles in the How to Catch series!",
    image: "https://m.media-amazon.com/images/I/91jwRAg09EL._SY466_.jpg",
    price: 5.62,
    buyUrl: "https://www.amazon.com/How-Catch-Dinosaur-Adam-Wallace/dp/1492680524/ref=sr_1_5?crid=1IMDA3LMFTNTD&keywords=kids+books&qid=1707341956&sprefix=kids+books%2Caps%2C132&sr=8-5",
    keywords: ["child","reading","cheap"],
  },
  {
    name: "Choose Your Own Adventure 4-Book Boxed Set #1 (The Abominable Snowman, Journey Under The Sea, Space And Beyond, The Lost Jewels of Nabooti",
    description: "Step into adventure with this 4-book boxed set from the bestselling Choose Your Own Adventure series! Join young readers aged 9-12 on thrilling quests to find the Abominable Snowman, explore Atlantis, journey through space, and seek the Lost Jewels of Nabooti. Packed with action, mystery, and interactive choices, these classics are perfect for empowering young minds and inspiring a love for reading.",
    image: "https://m.media-amazon.com/images/I/81u19rFTxJL._SY466_.jpg",
    price: 18.39,
    buyUrl: "https://www.amazon.com/Abominable-Snowman-Journey-Nabooti-Adventure/dp/1933390948/ref=sr_1_1_sspa?crid=2P8HAZAOWO2L6&keywords=adventure+reading+book&qid=1707342048&sprefix=adventure+reading+book%2Caps%2C135&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["adventure","reading"],
  },
  {
    name: "Friends, Lovers, and the Big Terrible Thing: A Memoir",
    description: "Delve into the candid and poignant memoir of Matthew Perry, beloved star of Friends, as he shares his journey from childhood to fame, addiction, and recovery. With humor and honesty, Perry reveals the fractured family that shaped him, the allure of recognition, and the void he struggled to fill despite his success. Friends, Lovers, and the Big Terrible Thing is a heartfelt and eye-opening account of sobriety and resilience, offering hope to those facing similar challenges.",
    image: "https://m.media-amazon.com/images/I/81tdvyI0MeL._SY466_.jpg",
    price: 19.57,
    buyUrl: "https://www.amazon.com/Friends-Lovers-Big-Terrible-Thing/dp/1250866448/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1707342123&sr=8-8",
    keywords: ["biography","reading"],
  },
  {
    name: "iDOO Hydroponics Growing System Kit 12Pods, Indoor Garden with LED Grow Light, Loved Gift for Green Thumbs Valentines, Built-in Fan, Auto-Timer, Adjustable Height Up to 11.3' for Home, Office",
    description: "Experience 20% faster plant growth with our hydroponic growing system kit, featuring a low-noise pump for aeration and a built-in fan to spread pollen and disperse heat. With a 4.5L water tank and easy setup, this system supports up to 12 plants at a time, offering two growing modes for optimal results.",
    image: "https://m.media-amazon.com/images/I/7102vcrm+XL._AC_SX679_.jpg",
    price: 63.98,
    buyUrl: "https://www.amazon.com/iDOO-Hydroponics-Germination-Adjustable-ID-IG301/dp/B08DLMRKHM/ref=sr_1_1_sspa?crid=3CFEDZ0HBJU9G&keywords=gardening%2Bgifts&qid=1707342247&sprefix=gardening%2Bgift%2Caps%2C131&sr=8-1-spons&ufe=app_do%3Aamzn1.fos.006c50ae-5d4c-4777-9bc0-4513d670b6bc&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    keywords: ["gardening"],
  },
  
  {
    name: "Night Vision Goggles - 4K Night Vision Binoculars for Adults, 3'' Large Screen Binoculars can Save Photo and Video with 32GB Memory Card & Rechargeable Lithium Battery",
    description: "Capture clear photos and videos in darkness with our night vision goggles, featuring 4K Full HD video resolution and 36MP photos. With a 3' TFT LCD screen, rechargeable lithium battery, and included 32GB SD card, these goggles are perfect for outdoor activities, wildlife watching, and surveillance.",
    image: "https://m.media-amazon.com/images/I/718VA2LT3HL._AC_SX466_.jpg",
    price: 105.98,
    buyUrl: "https://www.amazon.com/Night-Vision-Goggles-Binoculars-Rechargeable/dp/B0B12CD9YV/ref=sr_1_9?crid=2D0NSDZDTN4Y7&keywords=tech%2Bgifts&qid=1707342334&sprefix=tech%2Bgift%2Caps%2C132&sr=8-9&th=1",
    keywords: ["tech","gadgets","affordable"],
  },
  {
    name: "SGSPORT Disc Golf Basket with Discs | Portable Disc Golf Target with Heavy Duty 24-Chains Disc Golf Course Basket, Come with 6pcs Disc Golf Discs with Carry Bag",
    description: "Enjoy hours of fun with our heavy-duty disc golf basket, featuring anti-rust powder-coated steel construction and sturdy 24-chain rack for better catching. Easy to assemble and portable, it includes a starter disc golf set, making it the perfect gift for adults and outdoor enthusiasts.",
    image: "https://m.media-amazon.com/images/I/718mGh0AZdL._AC_SX679_.jpg",
    price: 135.99,
    buyUrl: "https://www.amazon.com/SGSPORT-Basket-Portable-Target-24-Chains/dp/B094DS26Q6/ref=sr_1_2_sspa?crid=12P6KV9GU8RUL&keywords=sports%2Bgifts&qid=1707342528&sprefix=sports%2Bgift%2Caps%2C127&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    keywords: ["sports","affordable"],
  },
  {
    name: "Easy Play Sports and Outdoors, for 3+ Years Old Kids & Adults - Complete Sports Ball Set in Carry Bag - Sport Balls Kit with Pump - Ideal for Boys' Outdoor Play and Convenient Storage",
    description: "Get ready for versatile outdoor fun with our all-inclusive sports ball set! This set includes branded football, soccer, basketball, volleyball, and playground balls, along with a convenient ball bag pump. Keep your gear organized and protected with the included storage bag, crafted from heavy-duty canvas with robust handles and a shoulder strap for easy transportation. Made from premium materials, our sports balls are built to last. Plus, rest easy knowing you're supporting a small, Veteran-owned business in the USA.",
    image: "https://m.media-amazon.com/images/I/71py0BeoImL._AC_SX679_.jpg",
    price: 78.19,
    buyUrl: "https://www.amazon.com/Easy-Play-Sports-Outdoors-Convenient/dp/B08FX9GJFL/ref=sr_1_11_sspa?crid=1WJEY6KMPARPW&keywords=sports%2Bball%2Bbag&qid=1707343428&sprefix=sports%2Bball%2Bbag%2Caps%2C142&sr=8-11-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1",
    keywords: ["sports","toys"],
  }, 
  {
    name: " Journeys Greatest Hits Remastered",
    description: "16 of Journeys most beloved recordings on 2 LPs. Features the all-time favorites 'Dont Stop Believin', 'Separate Ways (Worlds Apart)', 'Whos Crying Now' and 'Any Way You Want It'. Remastered from the original stereo master tapes and pressed on 180-gram audiophile vinyl.",
    image: "https://m.media-amazon.com/images/I/71NqTIW2GLL._SX425_.jpg",
    price: 35.97,
    buyUrl: "https://www.amazon.com/Greatest-Hits-Remastered-Journey/dp/B0CMZFG2HC/ref=sr_1_2_sspa?crid=3LX2QUZZCYE0Z&keywords=vinyl+records&qid=1707343559&sprefix=viny%2Caps%2C134&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ["music"],
  }, 
  {
    name: "SMPL One-Touch Music Player, Audiobooks + MP3, Quality-Sound, Durable Wooden Encloser with Retro Look, 4GB USB with 40 Nostalgic Hits Included, Live Technical Support (Red, Music + Radio Player)",
    description: "Experience all-in-one entertainment with the smpl one-touch music and radio player, featuring built-in high-quality speakers for immersive sound. Enjoy the nostalgic charm of a retro-style AM/FM radio and MP3 player, complete with a wooden enclosure. With extensive storage and pre-loaded hits, plus the option for battery power, take your music anywhere for outdoor adventures or travel.",
    image: "https://m.media-amazon.com/images/I/61xRSMSuPOL._AC_SX466_.jpg",
    price: 137.35,
    buyUrl: "https://www.amazon.com/One-Touch-Audiobooks-Quality-Sound-Nostalgic-Technical/dp/B07Z9JRVP7/ref=sxin_14_pa_sp_search_thematic_sspa?content-id=amzn1.sym.bb7ff370-0c07-41f7-b172-879ae394d746%3Aamzn1.sym.bb7ff370-0c07-41f7-b172-879ae394d746&crid=263B7FZ6WOHYU&cv_ct_cx=music%2Bplayer&keywords=music%2Bplayer&pd_rd_i=B095XD8VQJ&pd_rd_r=f6fa3d9a-e65f-4950-aaf6-9fa4e80891b3&pd_rd_w=GB3Ie&pd_rd_wg=sxF4d&pf_rd_p=bb7ff370-0c07-41f7-b172-879ae394d746&pf_rd_r=NPGF0HF6ZQT575XJSEKJ&qid=1707343648&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=music%2Bplaye%2Caps%2C131&sr=1-1-22b99f6c-9d79-4634-962b-718698cdc411-spons&ufe=app_do%3Aamzn1.fos.f5122f16-c3e8-4386-bf32-63e904010ad0&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1",
    keywords: ["music","tech","gadget"],
  }, 
  {
    name: "Harry Potter: The Complete 8-Film Collection",
    description: "Relive the adventure of Harry Potter and all 8 films in this boxed set",
    image: "https://m.media-amazon.com/images/I/81eVFzYBIdL._SY445_.jpg",
    price: 35.98,
    buyUrl: "https://www.amazon.com/Harry-Potter-Complete-8-Film-Collection/dp/B09WH576SQ/ref=sr_1_12_sspa?keywords=movies+physical+movie&qid=1707343815&sr=8-12-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1",
    keywords: ["movies","fantasy"],
  }, 
  {
    name: "Batman: 4-Film Collection 1989-1997",
    description: "Relive the Batman of yesterday in this boxed set",
    image: "https://m.media-amazon.com/images/I/712UgaQMZsL._SX342_.jpg",
    price: 32.54,
    buyUrl: "https://www.amazon.com/Batman-Motion-Picture-Anthology-1989-1997/dp/B07NSK3483/ref=sr_1_22_sspa?keywords=movies+physical+movie&qid=1707343953&sr=8-22-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1&smid=A12NTYNRXW6BWG",
    keywords: ["movies"],
  },
  {
    name: "MARVELS SPIDER-MAN 2  PS5 Launch Edition",
    description: "This launch edition of Marvels Spider-Man features the Arachknight Suit and Shadow-Spider Suit for Peter and Miles, along with the Web Grabber gadget and additional Skill Points. Play as both Spider-Men in an epic adventure across Marvels New York, facing off against iconic villains like Venom, Kraven the Hunter, and the Lizard. Experience an evolution of the Spider-Man story as Peter and Miles confront the ultimate test of strength while balancing their lives and duties.",
    image: "https://m.media-amazon.com/images/I/81VGpLvXQuL._AC_SX679_.jpg",
    price: 69.99,
    buyUrl: "https://www.amazon.com/MARVELS-SPIDER-MAN-2-Launch-PlayStation-5/dp/B0C7WNMCSC/ref=sr_1_2?crid=2I28U23SJI7WB&keywords=playstation+5+games&qid=1707344085&sprefix=playstation+5+game%2Caps%2C131&sr=8-2&ufe=app_do%3Aamzn1.fos.006c50ae-5d4c-4777-9bc0-4513d670b6bc",
    keywords: ["gaming"],
  }, 
  {
    name: "Madden NFL 24 - Xbox Series X and Xbox One",
    description: "Experience the next level of realism with SAPIEN technology, providing anatomically accurate NFL player skeletons for true-to-life motion. Enhanced control and FieldSENSE deliver a more responsive gameplay foundation. Customize your NFL career and legacy with game-changing control, while smarter AI ensures realistic player actions. Plus, enjoy Dual Entitlement for seamless upgrading from Xbox One to Xbox Series X|S. *Conditions apply.",
    image: "https://m.media-amazon.com/images/I/61heWfQE-1L._SX385_.jpg",
    price: 29.83,
    buyUrl: "https://www.amazon.com/Madden-NFL-24-Xbox-One-X/dp/B0C6NPMVG7/ref=sr_1_2?crid=3EVFZ5D4WJHFB&keywords=xbox%2Bsports%2Bgames&qid=1707344168&sprefix=xbox%2Bsports%2Bgame%2Caps%2C128&sr=8-2&th=1",
    keywords: ["gaming","sports"],
  },
  {
    name: "Glamzy Yellowstone The Complete Series Seasons 1-4 DVD (17 Disc) Box Set Season 1 2 3 4",
    description: "Return to Yellowstone and watch as the story is told ",
    image: "https://m.media-amazon.com/images/I/716OX3MV4cL._AC_SY606_.jpg",
    price: 48.00,
    buyUrl: "https://www.amazon.com/Glamzy-Yellowstone-Complete-Seasons-Season/dp/B0C7GVK5HH/ref=sr_1_10?crid=1QP63P71E0X7Q&keywords=tv+shows+bluray&qid=1707344249&sprefix=tv+shows%2Caps%2C134&sr=8-10",
    keywords: ["tv-shows","history"],
  },
  {
    name: "Stargate Collection - All Three Series Stargate Atlantis, Stargate SG-1, Stargate Universe",
    description: "Jump back into all the Stargate shows from tv. Make your way through the gate and hold on.",
    image: "https://m.media-amazon.com/images/I/51dBVuugvjS._SX466_.jpg",
    price: 109.99,
    buyUrl: "https://www.amazon.com/Stargate-Collection-Three-Atlantis-Universe/dp/B08M6GT3VL/ref=sr_1_12_sspa?crid=1DSO4QL9Z8NQ2&keywords=sopranos+complete+series&qid=1707344455&sprefix=sopranos+complete+serie%2Caps%2C127&sr=8-12-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1",
    keywords: ["tv-shows","sci-fi"],
  },
  {
    name: "Microwave Popcorn Popper with Temperature Safe Glass",
    description: "This BPA-free gadget allows for easy and healthy popcorn preparation in the microwave, offering a quick, tasty, and mess-free snack for movie nights or anytime enjoyment.",
    image: "https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/710PGXTh-4L._AC_SL1500_.jpg",
    price: 16.35,
    buyUrl: "https://www.amazon.com/Ecolution-Microwave-Micro-Pop-Borosilicate-Dishwasher/dp/B09CX95397/ref=sr_1_3?crid=165MOON0SD2K0&keywords=Ecolution+Patented+Micro-Pop+Microwave+Popcorn+Popper+with+Temperature+Safe+Glass%2C+3-in-1+Lid+Measures+Kernels+and+Melts+Butter%2C+Made+Without+BPA%2C+Dishwasher+Safe%2C+3-Quart%2C+Aqua&qid=1707361060&sprefix=ecolution+patented+micro-pop+microwave+popcorn+popper+with+temperature+safe+glass%2C+3-in-1+lid+measures+kernels+and+melts+butter%2C+made+without+bpa%2C+dishwasher+safe%2C+3-quart%2C+aqua%2Caps%2C335&sr=8-3",
    keywords: ["dining","kitchen","food"],
  },
  {
    name: "Miabella 18K Gold Over Sterling Silver Italian 5mm Mesh Link Chain Bracelet for Women",
    description: "8K gold over sterling silver 5mm Mesh bracelet, featuring interlocking links for a modern and polished look",
    image: "https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/71S2xqaxdWL._AC_SL1500_.jpg",
    price: 22.50,
    buyUrl: "https://www.amazon.com/dp/B07F42X2HP?th=1",
    keywords: ["jewelry","womens","adult"],
  },
  {
    name: "Birthdate Candles Zodiac Scented Candles",
    description: "Candles Inspired by the Stars: Your Zodiac sign, emblematic tarot card, ruling number and ruling planet",
    image: "https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61E4LvPD7NL._SL1500_.jpg",
    price: 42.49,
    buyUrl: "https://www.amazon.com/dp/B09WJ6X7VV?th=1",
    keywords: ["birthday","adult","candle"],
  },
  {
    name: "Napoleon P665RSIBPSS Prestige RSIB Propane Gas Grill, 665 sq. in + Infrared Side and Rear Burner, Stainless Steel",
    description: "The Napoleon Prestige 665 propane gas grill offers a complete outdoor kitchen experience with five main burners, an infrared rear and side burner, and iconic wave cooking grids, all housed in high-quality stainless steel for durability and enhanced cooking versatility.",
    image: "https://m.media-amazon.com/images/I/71dLqflG1IL._AC_SX679_.jpg",
    price: 1999.00,
    buyUrl: "https://www.amazon.com/Napoleon-P665RSIBPSS-Prestige-Infrared-Stainless/dp/B07MLFR4KZ/ref=sr_1_1_sspa?crid=30N02NS6H367Z&keywords=barbecue&qid=1707410980&sprefix=barbecue%2Caps%2C132&sr=8-1-spons&ufe=app_do%3Aamzn1.fos.17f26c18-b61b-4ce9-8a28-de351f41cffb&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    keywords: ["barbecue","cooking","adult","expensive","food","appliance"],
  },
  { 
    name: "oridom Preserved Flower Gift, Light Up Rose in Glass Dome, Eternal Forever Rose Flower Gifts for Her, Grandma, Mother’s Day, Valentine’s Day, Anniversary, Birthday, Christmas Decorations, Rose Pink",
    description: "Never Faded Rose: This forever rose in glass dome with soft and warm light is a symbol of eternal love and hope in the darkness, so is also a simple but meaningful gift for women, mother, grandma, wife, girlfriend on Mother’s Day and Valentine’s Day. We sincerely hope our glass rose flower gift can deliver love and good wishes, bring happiness and good luck to your loved ones especially those in difficult days.",
    image: "https://m.media-amazon.com/images/I/71aYSS-SNdL._AC_SX679_.jpg",
    price: "$18.99",
    buyUrl: "https://www.amazon.com/oridom-Preserved-Valentines-Anniversary-Decorations/dp/B0B3DSHSDH/ref=sr_1_6?crid=CT7YLEOLWKFD&keywords=flower&qid=1707777767&sprefix=flower%2Caps%2C165&sr=8-6&th=1",
    keywords: ""
  },
  { 
    name: "roliys Preserved Real Roses with Colorful Mood Light Wishing Bottle, Eternal Rose，Never Withered Flowers, Table Decor,Christmas Anniversary Valentine's, Blue 4.3inch, 1pcs",
    description: "Preserved flower, also named ‘never withered flower’ and ‘eternal flower’ etc, it’s preserved with high quality flowers.",
    image: "https://m.media-amazon.com/images/I/71MjVmCeCxL._AC_SX679_.jpg",
    price: "$32.99",
    buyUrl: "https://www.amazon.com/Preserved-Roses-Wishing-Rose%EF%BC%8CNever-Decorations/dp/B07DT2GBT2/ref=sr_1_25?crid=CT7YLEOLWKFD&keywords=flower&qid=1707778079&sprefix=flower%2Caps%2C165&sr=8-25&th=1",
    keywords: ""
  },
  { 
    name: "PAPERAGE Lined Journal Notebooks, 10 Pack, (Rainbow), 160 Pages, Medium 5.7 inches x 8 inches - 100 gsm Thick Paper, Hardcover",
    description: "BEST-SELLING HARDCOVER JOURNAL: This medium 5.7 in by 8 in lined notebook features durable and water-resistant vegan leather cover, rounded corners, 160 pages, inner expandable pocket, sticker labels, ribbon bookmark & elastic closure band.",
    image: "https://m.media-amazon.com/images/I/81KZ3puYxwL._AC_SX425_.jpg",
    price: "$62.95",
    buyUrl: "https://www.amazon.com/PAPERAGE-Journal-Notebooks-Rainbow-Medium/dp/B0BC2DFCJF/ref=sxin_14_pa_sp_search_thematic?content-id=amzn1.sym.5268d850-b53a-4d2b-93db-c4d525be24eb%3Aamzn1.sym.5268d850-b53a-4d2b-93db-c4d525be24eb&crid=2LDMNILFHIZB4&cv_ct_cx=notebook&keywords=notebook&pd_rd_i=B0BC2DFCJF&pd_rd_r=a0bb8c2d-7f5f-4468-869c-ddcc842148e3&pd_rd_w=pTZbd&pd_rd_wg=Q0BPx&pf_rd_p=5268d850-b53a-4d2b-93db-c4d525be24eb&pf_rd_r=SSQ1Z45E8K5D0DRA28K6&qid=1707778323&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=not%2Caps%2C273&sr=1-4-e7845da7-4b73-4873-b4b5-aec156390e83-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1",
    keywords: ""
  },
  { 
    name: "Scriveiner Silver Chrome Rollerball Pen - Stunning Luxury Pen with 24K Gold Finish, Schmidt Ink Refill, Best Roller Ball Pen Gift Set for Men & Women, Professional, Executive Office, Nice, Fancy Pens",
    description: "ENJOY THE FEEL OF A TRUE LUXURY PEN IN YOUR HAND – Brass with silver chrome finished in 24 karat gold. Premium quality and understated luxury from a boutique British brand.",
    image: "https://m.media-amazon.com/images/I/71Y2swR8sUL._AC_SX425_.jpg",
    price: "$32.99",
    buyUrl: "https://www.amazon.com/Luxury-Pen-Scriveiner-London-Professional/dp/B07YV85NNB/ref=pd_ci_mcx_pspc_dp_d_2_i_4?pd_rd_w=IjNkp&content-id=amzn1.sym.568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_p=568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_r=FF49D0RZCK7EE2SB0JJR&pd_rd_wg=S31eG&pd_rd_r=aa3084e3-d69e-4776-abe6-2d6e57990132&pd_rd_i=B07YV85NNB&th=1",
    keywords: ""
  },
  { 
    name: "Shuttle Art Wood-Cased #2 HB Pencils, 350 Pack Sharpened Yellow Pencils with Erasers, Bulk Pack Graphite Pencils for School and Teacher Supplies, Writing, Drawing and Sketching",
    description: "350 COUNT VALUE PACK: Shuttle Art 350 Pack #2 HB wood-cased yellow pencils in bulk are ideal choice for school, office and home to maintain daily pencil consumption. They are widely used in daily writhing, sketching, examination, marking, and more, especially for kids and teen writing in classroom and home.",
    image: "https://m.media-amazon.com/images/I/71IupKUoXzL._AC_SX425_.jpg",
    price: "	$27.99",
    buyUrl: "https://www.amazon.com/Wood-Cased-Shuttle-Art-Sharpened-Sketching/dp/B0891SSBJT/ref=sr_1_3?crid=1RK3PGGTDCMFU&keywords=pencils&qid=1707778649&s=office-products&sprefix=pencils%2Coffice-products%2C184&sr=1-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    keywords: ""
  },
  { 
    name: "FUNLAVIE Colored Pencils 72 Coloring Pencils Premium Professional Art Drawing Pencil for Adults Coloring Book",
    description: "Our Professional oil based colored pencils are made of high quality pencil lead which have strong tips,they don't break easily.Vibrant color goes on smooth and it blends easily,durable for your art creation.",
    image: "https://m.media-amazon.com/images/I/81IVfRGqfoL._AC_SX425_.jpg",
    price: "$14.99",
    buyUrl: "https://www.amazon.com/FUNLAVIE-Colored-Pencils-Coloring-Premium/dp/B0BJKGL4XY/ref=sr_1_14?crid=1DY8H5G4GV57M&keywords=colored%2Bpencils&qid=1707778882&s=office-products&sprefix=colored%2Bpencils%2Coffice-products%2C171&sr=1-14-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1",
    keywords: ""
  },
  { 
    name: "NAWOD Watercolor Paint Set, 50 Vivid Colors in Portable Box, Including Metallic and Fluorescent Colors, Watercolor Paper, Brushes. Ideal for Kids, Adults, Artists and Hobbyists, Perfect Starter Kit",
    description: "Amazing Quality for the Money: NAWOD watercolor paint set includes everything to start painting right away - 40 Basic colors, 5 Fluorescent colors and 5 Metallic Colors, 10 sheets of 300g Watercolor Paper, Metal Box, 6 Water Brush Pens, 10 Paint Brushes, Swatch Sheet, Sponge, Metal lid has 3 partitions and can be used as a mixing palette for easy blending of watercolors. The brushes and paper are individually wrapped, the solid pigments come in a sturdy metal box to prevent shipping or trip damage.",
    image: "https://m.media-amazon.com/images/I/81TAFeC+-RL._AC_SX569_.jpg",
    price: "$20.99",
    buyUrl: "https://www.amazon.com/Watercolor-Portable-Including-Fluorescent-Hobbyists/dp/B0CBGY6TCZ/ref=sxin_14_pa_sp_search_thematic?content-id=amzn1.sym.8a078810-42a9-4fda-b501-66b7ad65fd2c%3Aamzn1.sym.8a078810-42a9-4fda-b501-66b7ad65fd2c&crid=2WMY5ULF14CM9&cv_ct_cx=watercolor&keywords=watercolor&pd_rd_i=B0CBGY6TCZ&pd_rd_r=a9610b18-2d2a-4323-88ae-d1c7308ff36a&pd_rd_w=shmhI&pd_rd_wg=2E5MS&pf_rd_p=8a078810-42a9-4fda-b501-66b7ad65fd2c&pf_rd_r=DJ0654Z4CXDG9WJV60NS&qid=1707779079&s=office-products&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=watercolor%2Coffice-products%2C166&sr=1-4-d6c5bb1a-8f1a-4ada-8d3a-c85bd898008d-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&psc=1",
    keywords: ""
  },
  { 
    name: "Amazon Fire TV 32 inch 2-Series HD smart TV with Fire TV Alexa Voice Remote, stream live TV without cable",
    description: "High definition TV - Bring movies and shows to life in HD 720p resolution, with support for HDR 10, HLG, and Dolby Digital Audio.",
    image: "https://m.media-amazon.com/images/I/61CO+jrHHjL._AC_SX425_.jpg",
    price: "$119.99",
    buyUrl: "https://www.amazon.com/introducing-amazon-fire-tv-32-inch-2-series-hd-smart-tv/dp/B09N6F9NV3/ref=sr_1_4?crid=22Y9FSH7RAUBY&keywords=Television&qid=1707779324&sprefix=television%2Caps%2C187&sr=8-4",
    keywords: ""
  },
  { 
    name: "JBL FLIP 5, Waterproof Portable Bluetooth Speaker, Black, Small",
    description: "Pair multiple speakers with party boost",
    image: "https://m.media-amazon.com/images/I/61ZquNpiFcL._AC_SX425_.jpg",
    price: "$79.95",
    buyUrl: "https://www.amazon.com/JBL-Waterproof-Portable-Bluetooth-Speaker/dp/B07QK2SPP7/ref=sr_1_4?crid=CBOAGSO31Y7G&keywords=Speaker&qid=1707779526&sprefix=speaker%2Caps%2C209&sr=8-4&th=1",
    keywords: ""
  },
  { 
    name: "",
    description: "",
    image: "",
    price: "",
    buyUrl: "",
    keywords: ""
  },
];

module.exports = initialGifts;

/* Keyword Master List
'adult', 'adventure', 'affordable', 'anniversary', 'apparel', 'barbecue', 'bedroom', 'biography', 'birthday', 'black', 'book', 'candle', 'cheap', 
'child', 'childrens', 'christmas', 'coat', 'crime', 'dining', 'easter', 'expensive', 'fantasy', 'father', 'food', 'gadget', 'gadgets', 
'gaming', 'gardening', 'general', 'graduation', 'halloween', 'history', 'horror', 'housewarming', 'jewelry', 'kitchen', 'laundry', 'living-room', 
'mens', 'mother', 'movies', 'music', 'mystery', 'pink', 'reading', 'romantic', 'sci-fi', 'shirt', 'shoes', 'snacks', 'sports', 'tech', 'toy', 'toys', 
'tv', 'tv-shows', 'valentines', 'wellness', 'womens'
 */